// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service represents the notifications service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * RemoveBadge removes the badge label from the application icon.
 * @returns {$CancellablePromise<void>}
 */
export function RemoveBadge() {
    return $Call.ByID(2374916939);
}

/**
 * SetBadge sets the badge label on the application icon.
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function SetBadge(label) {
    return $Call.ByID(784276339, label);
}

/**
 * @param {string} label
 * @param {$models.Options} options
 * @returns {$CancellablePromise<void>}
 */
export function SetCustomBadge(label, options) {
    return $Call.ByID(3058653106, label, options);
}
